### ISSUE TITLE
TYQT Crashes on start

### ISSUE THREAD

**Issue by xorionfe** [Koromix/tytools#12] opened 2017-02-23 12:47 UTC
There seems to be a conflict with my MSI Motherboard onboard USB drivers.   It uses Asmedia drivers.   I had the same issue on an ASUS MB that was using Asmedia USB drivers.   I also see the problem if VIA USB drivers are present.  If I disable these then TYQT will start and work but I lose many of my usb ports in the process.   Can you please look into what might be causing the problem.   I am using the latest version 8 of TYQT.  I am a friend of Rob A and Jorg B and a cockpit builder building a 737-200 similiar to Rob's.  I will be using upwards of 20 Teensys so your program is much needed and much appreciated.

Here is the error in the crash:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	TyQt.exe
  Application Version:	0.0.0.0
  Application Timestamp:	581e0930
  Fault Module Name:	TyQt.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	581e0930
  Exception Code:	c0000005
  Exception Offset:	0000000000d31480
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	aa8b
  Additional Information 2:	aa8b8565f92a21edea6add95009a38df
  Additional Information 3:	28ac
  Additional Information 4:	28ac02407e34c72c3170e7d5d407e38b

In order to get TYQT to load I have to disable the below drivers circled in Red
![image](https://cloud.githubusercontent.com/assets/25981293/23259675/d1db6ef0-f993-11e6-8ec1-39bcf8e025b6.png)

Thank you,
Scott Wegner

**Comment by Koromix** [comment] 2017-02-23 12:56
Well that's certainly a problem :) Could you try the latest development build, the application is now named TyCommander? There have been several changes in the Win32 device code since the latest release 0.8.0.

Direct links to this version:
- https://bintray.com/koromix/tytools/download_file?file_path=TyTools-0.8.0-102-g7b89d86-win32.msi
- https://bintray.com/koromix/tytools/download_file?file_path=TyTools-0.8.0-102-g7b89d86-win32.zip

**Comment by xorionfe** [comment] 2017-02-23 13:00
Thank you Neils.  I will give it a try and report back.

Best regards,
Scott Wegner

**Comment by xorionfe** [comment] 2017-02-23 14:08
Unfortunately Tycommander exhibits the same crash

Problem signature:
  Problem Event Name: APPCRASH
  Application Name: TyCommander.exe
  Application Version: 0.0.0.0
  Application Timestamp: 58a9b0ab
  Fault Module Name: TyCommander.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp: 58a9b0ab
  Exception Code: c0000005
  Exception Offset: 000a4930
  OS Version: 6.1.7601.2.1.0.256.48
  Locale ID: 1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by xorionfe** [comment] 2017-02-23 14:10
if I disable the below devices then Tycommander starts fine

[image: Inline image 1]

**Comment by Koromix** [comment] 2017-02-23 14:57
I really need to produce a log file for this kind of crash. In the meantime, could you put the batch file in the ZIP below in the TyCommander directory and run it?

It will try to start TyCommander in debug mode and output the debug log in a text file "TyCommander_<DATE>_Log.txt" in the desktop directory. Then you can send me this file.

[TyCommander_Debug.zip](https://github.com/Koromix/tytools/files/796761/TyCommander_Debug.zip)

**Comment by xorionfe** [comment] 2017-02-23 15:09
Tried to run it but it fails to run

[image: Inline image 1]

**Comment by jbliesener** [comment] 2017-02-23 15:11
Scott, I'm following this as well. Can you try to re-upload the picture you were attaching? Didn't come through...

**Comment by xorionfe** [comment] 2017-02-23 15:16
![image](https://cloud.githubusercontent.com/assets/25981293/23264963/c66c0e5c-f9a8-11e6-8e9b-92922d3f370a.png)

**Comment by Koromix** [comment] 2017-02-23 15:23
Not sure why the batch code fails but this is why I hate batch... Although it could be because you run an Administrator command prompt, so it fails to find the desktop directory.

Can't test if that's the cause, no admin access on my work computer.

To output the log data, do "set TY_DEBUG=1" in the console and then execute "TyCommanderC.exe run". It'll give you the debug output in the console.

**Comment by xorionfe** [comment] 2017-02-23 15:38
Here is result

![image](https://cloud.githubusercontent.com/assets/25981293/23265893/cc3ba8d0-f9ab-11e6-9100-e534702893f0.png)

**Comment by Koromix** [comment] 2017-02-23 15:45
Thank you, that gives me a pretty good idea of what goes wrong and how to reproduce without access to these USB controllers.

I'll push a (potential) fix tonight.

**Comment by xorionfe** [comment] 2017-02-23 15:46
Thank you Niels.   If you need anything else I am around most of the day at
my home office so can test stuff.

**Comment by Koromix** [comment] 2017-02-23 22:16
I've pushed a few fixes that may or may not help with this problem... More importantly, the latest build adds a crash memory dumper to TyCommander to help me track this issue.

https://bintray.com/koromix/tytools/tytools/view#files
Get build TyTools-0.8.0-107-ge5c1e9a

Get this build, start TyCommander.exe and send me the memory dump that gets saved in "C:\Users\<NAME>\AppData\Local\CrashDumps". Well, if it works. It does on my computer but so did the batch file...

**Comment by xorionfe** [comment] 2017-02-24 00:04
Crashed again

Here are the dmp files.   Looks like it created two of them.

Scott

**Comment by Koromix** [comment] 2017-02-24 06:15
Sorry, the two files are not in your post. GitHub probably failed with the mail attachments.

You can send me the files directly if you prefer: niels.martignene@gmail.com

**Comment by Koromix** [comment] 2017-02-24 19:16
The crash should be fixed in TyTools-0.8.0-110-g9fdf575.

Can you confirm that first, the crash does not happen anymlore and two, that TyCommander detects Teensy devices when they are plugged in the USB ports controlled by the VIA and ASMedia host controllers?

**Comment by xorionfe** [comment] 2017-02-24 19:31
Thank you Niels.  I will try it again after work tonight when I get home
and report back.

**Comment by xorionfe** [comment] 2017-02-24 21:48
Just got home.  It is working!   and yes, I am able to use no matter which
of the ports I plug into.  It seems to be working perfect.   Thank you.
Without this program managing all the Teensys I am about to have running
this sim would be difficult.  I appreciate you making it and fixing it to
work with these drivers.   If there is somewhere I can send a little
donation please let me know.

Scott

**Comment by Koromix** [comment] 2017-02-25 08:11
Glad to see it works! Thanks for you help in fixing this issue. I will ship the 0.8.1 release soon, mainly to include this fix.

I have a Paypal page up if you want: https://www.paypal.me/nielsmartignene
But I don't even know how / if this page works. The Paypal account does work, it is linked to niels.martignene@gmail.com.

**Comment by xorionfe** [comment] 2017-02-25 18:34
As an FYI, the upload functionality is not working.  It hangs.  I then
reset the Teensy in question by pressing its reset button and it appears to
load then errors out.   Will wait for your 8.1 release and try again.

Scott

**Comment by Koromix** [comment] 2017-02-25 19:39
Does the serial monitor work correctly, at least? And does upload work on a USB 2.0 port, if you have one?

USB 3.0 controllers are annoying on Windows < 10, because unlike USB 2.0 controllers they each use a specific constructor driver... and those tend to exhibit various bugs. Simply looking at them the wrong way can cause weird stuff.

I've used your donation to buy a VIA PCI USB 3.0 controller to test stuff on it. It'll be here in a few days, so I can test TyCommander on it.

**Comment by xorionfe** [comment] 2017-02-25 20:55
I just pulled the via hub out and moved my connections over onto the main board and seems to be fine now uploading

**Comment by Koromix** [comment] 2017-02-25 21:22
I'm not surprised. I've known for a long time that USB 3.0 controllers on Windows < 10 are hit and miss with this program.

I've found both a VIA and an ASMedia PCI-E to USB 3.0 cards, both pretty cheap, to test and fix the issue. They should arrive next week. Thanks for the donation!

**Comment by xorionfe** [comment] 2017-02-25 22:41
It wasn't only with your program.  I was seeing some other usb problems with the teensys in x-plane.   They were also connecting through usb 2.0 hubs.   Moving the hubs and removing the via card seems to have resolved for now.    I guess it is all about the correct combination and maybe some hubs are a little sensitive to the type of usb chipset they are connecting to.

**Comment by Koromix** [comment] 2017-05-28 10:29
I've made a new release, TyTools 0.8.5. There's not much new beyond UI changes since we've fixed this issue.

The (lightweight) testing I've done with the boards I've received has not revealed any issue so I'm closing this for now.

**Closed by Koromix** 2017-05-28 10:29 UTC
Labels: bug
